export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
