export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
